# Variables dentro de loops
# ansible_loop.allitems       La lista de todos los elementos en el bucle
# ansible_loop.index          La iteración actual del bucle. (comenzando en 1)
# ansible_loop.index0         La iteración actual del bucle. (comenzando en 0)
# ansible_loop.revindex       El número de iteraciones hasta acabar el bucle (comenzando en 1)
# ansible_loop.revindex0      El número de iteraciones hasta acabar el bucle (comenzando en 0)
# ansible_loop.first          Verdadero si es la primera iteración
# ansible_loop.last           Verdadero si es la última iteración
# ansible_loop.length         El número de elementos en el bucle
# ansible_loop.previtem       El elemento de la iteración anterior del bucle. Indefinido durante la primera iteración.
# ansible_loop.nextitem       El elemento de la siguiente iteración del bucle. Indefinido durante la última iteración.

- hosts: ubuntu01

  remote_user: root
  order: inventory
  
  
  tasks:
    - name: Mi  tarea de facts
      debug:
        msg: " {{ item }}"
      
      
      loop: "{{ ansible_processor }}" 
      loop_control:
        index_var: cpus
      when: (cpus+1) % 3 == 0
 
 ###
# Filtros jinja2
#
# abs, attr, batch, capitalize, center, default, dictsort, escape, filesizeformat, first, float, forceescape, format, 
# groupby, indent, int, join, last, length, list, lower, map, max, min, pprint, random, reject, rejectattr, replace, 
# reverse, round, safe, select, selectattr, slice, sort, string, striptags, sum, title, tojson, trim, truncate, unique, 
# upper, urlencode, urlize, wordcount, wordwrap, xmlattr
#
# Uso {{ variable | upper }}
#
# https://jinja.palletsprojects.com/en/2.11.x/templates/#builtin-filters
